### ISSUE TITLE
Support modern versions of node

### ISSUE THREAD

**Issue by solleedev** [aragon/osx-cli#14]
I've been using Node 18 and having troubles with Aragon CLI:
```
Detected node version: 18.17.0. Required node version: >=10.0.0 <11 || >=12.0.0 <13.
```

I also tried to downgrade to the latest version of Node 12, however it gave errors when running the CLI:

```
Error: Cannot find module 'node:crypto'
Require stack:
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@noble+hashes@1.3.1/node_modules/@noble/hashes/cryptoNode.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@noble+hashes@1.3.1/node_modules/@noble/hashes/utils.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@noble+hashes@1.3.1/node_modules/@noble/hashes/_sha2.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@noble+hashes@1.3.1/node_modules/@noble/hashes/sha256.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@noble+curves@1.1.0/node_modules/@noble/curves/secp256k1.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/ethereum-cryptography@2.1.2/node_modules/ethereum-cryptography/secp256k1.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@ethereumjs+util@8.1.0/node_modules/@ethereumjs/util/dist/constants.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@ethereumjs+util@8.1.0/node_modules/@ethereumjs/util/dist/index.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/web3-utils@1.10.2/node_modules/web3-utils/lib/utils.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/web3-utils@1.10.2/node_modules/web3-utils/lib/index.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@aragon+cli@7.1.6_@babel+core@7.22.15_eslint@8.48.0_ws@8.14.0/node_modules/@aragon/cli/dist/cli.js
- /home/sollee/.local/share/pnpm/global/5/.pnpm/@aragon+cli@7.1.6_@babel+core@7.22.15_eslint@8.48.0_ws@8.14.0/node_modules/@aragon/cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sollee/.local/share/pnpm/global/5/.pnpm/@noble+hashes@1.3.1/node_modules/@noble/hashes/src/cryptoNode.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```

**Comment by solleedev** [comment]
Installed with `pnpm i -g @aragon/cli` btw

**Comment by pythonpete32** [comment]
Sorry for the late response, I have beed away on leave. Unfortunately we could not use `@aragon/cli` namespace because the old cli (for the previous OSx) has it. The new namespace is `pnpm i -g @aragon/osx-cli`. I have updated the readme
